version: 3.1.0
pipeline_os: linux
main_branch: dynamo_py3

build:
  -
    customized_builder_image:
      registry: artifactory
      url: artifactory.dev.adskengineer.net/dynamo/pythonnet-build:2.0.1
    scripts:
      - scripts/install.sh

soc2:
  harmony:
    allow_branches:
      - PR-
      - dynamo_master
      - dynamo_py3
    third_party_lib_paths:
      - build\lib\pythonnet\runtime
    analyze_results	: true
